language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
# Configure a headless display to test plot generation
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
# Install any dependencies for running the tests:
install: pip install codecov pytest-cov matplotlib
# command to run tests
script: py.test --cov=oommffield --cov-config .coveragerc
after_success:
  codecov
